name: lili_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  build_runner: ^2.4.8
  camera: ^0.10.5+9
  card_swiper: ^3.0.1
  cloud_firestore: ^4.15.0
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^3.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.11
  firebase_storage: ^11.6.3
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_datetime_picker_plus: ^2.1.0
  flutter_hooks: ^0.20.4
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_line_sdk: ^2.3.6
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_sms: ^2.3.3
  flutter_staggered_grid_view: ^0.7.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.9
  image_cropper: ^5.0.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  intl: ^0.18.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9
  timezone: ^0.9.2
  url_launcher: ^6.2.4
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
  fonts:
    - family: Normal
      fonts:
         - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
           weight: 500
         - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
           weight: 600
         - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
           weight: 700
         - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
           weight: 800
         - asset: assets/font/Noto_Sans_JP/NotoSansJP-VariableFont_wght.ttf
           weight: 900

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/img/logo.png"

flutter_native_splash:
  image: "assets/img/logo.png"
  color: "000000"
