name: lili_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9

  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:


  uses-material-design: true


